name: Deploy Microservice Comments  to Amazon ECS

on:
  push:
    paths:
      - 'DMicroservicioComentarios/**'
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 339712766050.dkr.ecr.us-east-2.amazonaws.com
  ECR_REPOSITORY: grupo14-mcsrv-comments
  ECS_SERVICE: srv-update-movies_
  ECS_CLUSTER: g14-microservices_
  CONTAINER_NAME: updateMovie_
  TASK_DEFINITION_NAME: task-microservicios-g14_

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ./DMicroservicioComentarios
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

     